config/routes.rb
DocIndexer::Application.routes.draw do
  resources :documents do
    collection do
      get :search
    end
  end

  root :to => 'documents#index'

end

app/models/document.rb
require 'ruby_tika_app'

class Document < ActiveRecord::Base
  mount_uploader :doc, DocumentUploader
  paginates_per 30

  def extract_content
    rta = RubyTikaApp.new(self.doc.current_path)
    begin
      self.content = rta.to_text
      self.indexed = true
    rescue
      self.indexed = false
    end
    self.save
  end

  searchable do
    text :content, :stored => true
    boolean :indexed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/documents_controller.rb
class DocumentsController < InheritedResources::Base

  has_scope :page, :default => 1

  def search
    @documents = Document.search do
      fulltext params[:query] do
        highlight :content
      end
      with :indexed, true
      paginate page: params[:page]
    end

    respond_to do |format|
      format.html 
      format.json { render json: @documents }
    end
  end

  def create
    create! do |format|
      if @document.errors.empty? && @document.extract_content
        format.html { redirect_to documents_path, notice: 'Document was successfully created.' }
        format.json { render json: @document, status: :created, location: @document }
      else
        format.html { render action: "new" }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    update! do |format|
      if @document.errors.empty? && @document.extract_content
        format.html { redirect_to document_path notice: 'Document was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  private 

  def permitted_params
    params.permit(:document => [:title, :doc])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.erb
<%= form_for(@document) do |f| %>
  <% if @document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% @document.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br />
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :doc, 'Please self a file to upload' %><br />
    <%= f.file_field :doc %>
  </div>

  <div class="actions">
    <%= f.button 'Upload Document', type: :submit, class: 'btn btn-primary' %>
    <%= link_to 'Back', documents_path, class: 'btn btn-warning' %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<h1>Edit Document</h1>

<%= render 'form' %>

app/views/documents/index.html.erb
<%= render 'shared/teaser' %>
<div class="row">

  <%= form_tag search_documents_path, method: :get do %>

    <div class="col-lg-7">
      <div class="input-group">
        <%= text_field_tag :query, params[:query], class: 'form-control', placeholder: "Enter search term" %>
        <span class="input-group-btn">
          <%= button_tag "Search Documents", type: 'submit', class: 'btn btn-large btn-primary' %>
        </span>
      </div><!-- /input-group -->
    </div><!-- /.col-lg-6 -->

  <% end %>

</div><!-- /.row -->


<div class="documents">

<h2>Recently Uploaded Documents</h2>

<table class="table table-striped">
  <tr>
    <th>Title</th>
    <th></th>
    <th></th>
    <!--<th></th>-->
  </tr>

<% @documents.each do |document| %>
  <tr>
    <td><strong><%= link_to document.title, document %></strong></td>
    <td><%= link_to 'View/Download', document.doc.url, target: "_blank" %></td>
    <td><%= link_to 'Edit', edit_document_path(document) %></td>
    <!--<td><%= link_to 'Destroy', document, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
  </tr>
<% end %>
<% if @documents.empty? %>
  <tr><td colspan="4">No documents found</td></tr>
<% end %>
</table>

</div>

<% paginate @documents %>

<%= link_to 'New Document', new_document_path, class: 'btn btn-primary' %>

app/views/documents/new.html.erb
<h1>Upload a New Document</h1>

<%= render 'form' %>

app/views/documents/search.html.erb
<div class="row">

  <%= form_tag search_documents_path, method: :get do %>
    <div class="col-lg-7">
      <div class="input-group">
        <%= text_field_tag :query, params[:query], class: 'form-control', placeholder: "Enter search term" %>
        <span class="input-group-btn">
          <%= button_tag "Search Documents", type: 'submit', class: 'btn btn-large btn-primary' %>
        </span>
      </div><!-- /input-group -->
    </div><!-- /.col-lg-6 -->

  <% end %>

</div><!-- /.row -->

<div class="row result-count">
  <div class="col-lg-6"><%= pluralize @documents.total, "result" %> for "<%= params[:query] %>" found</div>
</div>

<% @documents.each_hit_with_result do |hit, document| %>
  <div class="search-result">
    <h3><%= link_to document.title, document %></h3>
    <p>
      <% unless hit.highlights(:content).empty? %>
        <%= raw hit.highlights(:content)[0].format { |word| "<strong>#{word}</strong>" } %>
      <% end %>
    </p>
    <p>
      <%= link_to '<span class="glyphicon glyphicon-download"></span> View/Download'.html_safe , document.doc.url, target: "_blank" %>
      <%= link_to '<span class="glyphicon glyphicon-edit"></span> Edit'.html_safe , edit_document_path(document) %>
    </p>
  </div>
<% end %>
<% if @documents.total == 0 %>
  <p>No documents found</p>
<% end %>

<% paginate @documents.hits %>

app/views/documents/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @document.title %></h1>

<h3>Document</h3>
<p><%= link_to 'Download', @document.doc.to_s %></p>


<h3>Content</h3>
<p class="body">
  <%= simple_format @document.content %>
</p>

<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', documents_path %>

app/views/layouts/application.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %meta{:content => "", :name => "description"}/
    %meta{:content => "", :name => "author"}/
    %link{:href => "/favicon.png", :rel => "shortcut icon"}/
    %title Open Library
    = stylesheet_link_tag    "application", :media => "all"
    = csrf_meta_tags
  %body
    .navbar.navbar-inverse.navbar-fixed-top
      .container
        .navbar-header
          %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to 'Philippine Open Library', root_path, class: 'navbar-brand'
        .collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li{ :class => ("active" unless action_name == "search") }
              = link_to 'Home', root_path
            %li
              = link_to 'Upload a Document', new_document_path
            %li
              = link_to 'About', 'https://www.facebook.com/groups/pinoypug/permalink/612637275452970/'
            %li
              = link_to 'Contact', 'https://www.facebook.com/groups/214546845336651/'

        / /.nav-collapse
    .container
      = yield
    = javascript_include_tag "application"

app/views/shared/_teaser.haml
.container
  .starter-template
    %h1 The Philippine Open Library
    %p.lead
      A site to easily and quickly upload public government documents
      %br/